spring:
  profiles.active: ${ENV:dev}

server.port: ${PORT:8080}

management.server.port: ${PORT2:8081}
management.server.address: 127.0.0.1

config:
  bcryptSalts: 12

logging.file: elk-store.log
spring.application.name: storeservice
